global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'telegram'
  routes:
    - matchers:
        - severity="critical"
      receiver: 'telegram'
      group_wait: 5s
      repeat_interval: 30m
    - matchers:
        - severity="warning"
      receiver: 'telegram'
      repeat_interval: 2h

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: '8803629249:AAGgsVPtKpGdWBgmXtrd3u8_SQDMpKxWXzY'
        chat_id: 7665819292
        parse_mode: 'HTML'
        send_resolved: true          # добавляем – теперь будет приходить сообщение о восстановлении
        message: |
          {{ range .Alerts }}
          <b>{{ .Labels.alertname }}</b> [{{ .Labels.severity }}]
          {{ .Annotations.summary }}
          
          {{ .Annotations.description }}
          
          <i>Started: {{ .StartsAt.Format "2006-01-02 15:04:05" }}</i>
          {{ if ne .Status "resolved" }}<i>Status: {{ .Status }}</i>{{ end }}
          {{ end }}
